export const AGRERGAR_PRODUCTO = 'AGRERGAR_PRODUCTO';
export const AGRERGAR_PRODUCTO_EXITO = 'AGRERGAR_PRODUCTO_EXITO';
export const AGRERGAR_PRODUCTO_ERROR = 'AGRERGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGAR_PRODUCTOS = 'COMENZAR_DESCARGAR_PRODUCTOS'
export const COMENZAR_DESCARGAR_EXITO = 'COMENZAR_DESCARGAR_EXITO'
export const COMENZAR_DESCARGAR_ERROR = 'COMENZAR_DESCARGAR_ERROR' 